TRAIT_CATALOG = [
    {
        "key": "opening_plan_clarity",
        "name": "Opening Plan Clarity",
        "category": "opening",
        "description": "How consistently the player forms a clear middlegame plan from the opening position.",
        "severity_weight": 1.0,
    },
    {
        "key": "development_consistency",
        "name": "Development Consistency",
        "category": "opening",
        "description": "How reliably the player develops pieces smoothly before starting side operations.",
        "severity_weight": 1.0,
    },
    {
        "key": "king_safety_prioritization",
        "name": "King Safety Prioritization",
        "category": "opening",
        "description": "How often king safety is handled on time relative to other opening goals.",
        "severity_weight": 1.0,
    },
    {
        "key": "opening_flexibility",
        "name": "Opening Flexibility",
        "category": "opening",
        "description": "How well the player adapts when opponents choose unfamiliar or offbeat setups.",
        "severity_weight": 1.0,
    },
    {
        "key": "opening_time_balance",
        "name": "Opening Time Balance",
        "category": "opening",
        "description": "How effectively the player balances speed and care during early opening decisions.",
        "severity_weight": 1.0,
    },
    {
        "key": "threat_detection",
        "name": "Threat Detection",
        "category": "tactics",
        "description": "How consistently immediate opponent threats are noticed before committing to a move.",
        "severity_weight": 1.0,
    },
    {
        "key": "candidate_move_scan",
        "name": "Candidate Move Scan",
        "category": "tactics",
        "description": "How regularly the player checks multiple tactical candidates instead of the first idea only.",
        "severity_weight": 1.0,
    },
    {
        "key": "forcing_move_discipline",
        "name": "Forcing Move Discipline",
        "category": "tactics",
        "description": "How often checks, captures, and direct threats are reviewed in a structured way.",
        "severity_weight": 1.0,
    },
    {
        "key": "loose_piece_awareness",
        "name": "Loose Piece Awareness",
        "category": "tactics",
        "description": "How attentive the player is to undefended or overloaded pieces on both sides.",
        "severity_weight": 1.0,
    },
    {
        "key": "counterplay_alertness",
        "name": "Counterplay Alertness",
        "category": "tactics",
        "description": "How well the player anticipates tactical counter-chances while pressing their own ideas.",
        "severity_weight": 1.0,
    },
    {
        "key": "pawn_structure_attention",
        "name": "Pawn Structure Attention",
        "category": "strategy",
        "description": "How consistently pawn-structure strengths and weaknesses guide strategic choices.",
        "severity_weight": 1.0,
    },
    {
        "key": "piece_activity_priority",
        "name": "Piece Activity Priority",
        "category": "strategy",
        "description": "How reliably piece activity is favored over passive material-preserving play.",
        "severity_weight": 1.0,
    },
    {
        "key": "prophylactic_thinking",
        "name": "Prophylactic Thinking",
        "category": "strategy",
        "description": "How often the player considers and limits the opponent's next plan.",
        "severity_weight": 1.0,
    },
    {
        "key": "plan_transition_timing",
        "name": "Plan Transition Timing",
        "category": "strategy",
        "description": "How effectively the player shifts plans when position demands change.",
        "severity_weight": 1.0,
    },
    {
        "key": "simplification_judgment",
        "name": "Simplification Judgment",
        "category": "strategy",
        "description": "How well exchanges are chosen to support the position rather than reduce complexity by default.",
        "severity_weight": 1.0,
    },
    {
        "key": "king_activation_timing",
        "name": "King Activation Timing",
        "category": "endgame",
        "description": "How appropriately the king is brought into play once endgame conditions allow.",
        "severity_weight": 1.0,
    },
    {
        "key": "passed_pawn_management",
        "name": "Passed Pawn Management",
        "category": "endgame",
        "description": "How effectively passed pawns are created, advanced, and restrained in practical play.",
        "severity_weight": 1.0,
    },
    {
        "key": "conversion_technique",
        "name": "Conversion Technique",
        "category": "endgame",
        "description": "How consistently advantage is converted with clear, low-risk endgame plans.",
        "severity_weight": 1.0,
    },
    {
        "key": "defensive_endgame_tenacity",
        "name": "Defensive Endgame Tenacity",
        "category": "endgame",
        "description": "How resourcefully difficult endgames are defended to maximize drawing chances.",
        "severity_weight": 1.0,
    },
    {
        "key": "rook_endgame_fundamentals",
        "name": "Rook Endgame Fundamentals",
        "category": "endgame",
        "description": "How consistently core rook endgame principles are applied in practical positions.",
        "severity_weight": 1.0,
    },
    {
        "key": "critical_moment_time_usage",
        "name": "Critical Moment Time Usage",
        "category": "time",
        "description": "How well extra time is concentrated on high-impact decisions rather than routine moves.",
        "severity_weight": 1.0,
    },
    {
        "key": "move_pace_stability",
        "name": "Move Pace Stability",
        "category": "time",
        "description": "How steady the player's decision pace remains across different game phases.",
        "severity_weight": 1.0,
    },
    {
        "key": "time_trouble_frequency",
        "name": "Time Trouble Frequency",
        "category": "time",
        "description": "How often the player reaches severe clock pressure before the final phase.",
        "severity_weight": 1.0,
    },
    {
        "key": "increment_management",
        "name": "Increment Management",
        "category": "time",
        "description": "How effectively increment is used to preserve move quality under low time.",
        "severity_weight": 1.0,
    },
    {
        "key": "familiar_position_speed",
        "name": "Familiar Position Speed",
        "category": "time",
        "description": "How confidently the player makes efficient decisions in positions they recognize well.",
        "severity_weight": 1.0,
    },
    {
        "key": "error_recovery",
        "name": "Error Recovery",
        "category": "psych",
        "description": "How well the player regains focus and practical decision quality after a mistake.",
        "severity_weight": 1.0,
    },
    {
        "key": "risk_calibration",
        "name": "Risk Calibration",
        "category": "psych",
        "description": "How appropriately practical risk is matched to game situation and match context.",
        "severity_weight": 1.0,
    },
    {
        "key": "pressure_composure",
        "name": "Pressure Composure",
        "category": "psych",
        "description": "How stable decision-making remains in tense positions or must-win scenarios.",
        "severity_weight": 1.0,
    },
    {
        "key": "result_detachment",
        "name": "Result Detachment",
        "category": "psych",
        "description": "How consistently the player chooses moves based on position needs rather than score anxiety.",
        "severity_weight": 1.0,
    },
    {
        "key": "practical_resilience",
        "name": "Practical Resilience",
        "category": "psych",
        "description": "How persistently the player seeks practical chances in worse or unclear positions.",
        "severity_weight": 1.0,
    },
]
